services:
  mlops_service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cifar10_service
    ports:
      - "8000:8000"
    networks:
      - shared_network

networks:
  shared_network:
    driver: bridge
